config/routes.rb
Rails.application.routes.draw do

    root 'pages#index'

    get '/user/:id/delete' => 'users#delete'
    delete '/user' => 'users#destroy'
    get '/user/not_activated' => 'users#not_activated'
    get '/user/activate/:token' => 'users#activate'
    patch '/user/activate/:token' => 'users#set_activation'
    get '/invite' => 'users#new'
    post '/invite' => 'users#create'

    get '/session' => 'sessions#new'
    resource :sessions, path: 'session', only: [:new, :create, :destroy]

    get '/notes/:id/delete' => 'notes#delete'
    resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user
    acts_as_taggable

    validates :title, presence: true
    validates :content, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :authenticate!
    before_action :antiflood!, only: [:update, :create, :destroy]

    def index
        @user = User.find_by_id!(session[:user]['id'])
        @notes = @user.notes.order(updated_at: :desc)
    end

    def show
        @user = User.find_by_id!(session[:user]['id'])
        @note = @user.notes.find_by_id(params[:id])
        unless @note
            flash[:warning] = [t('controllers.notes.show.not_found')]
            redirect_to notes_path
        end
    end

    def edit
        @user = User.find_by_id!(session[:user]['id'])
        @note = @user.notes.find_by_id(params[:id])
        unless @note
            flash[:warning] = [t('controllers.notes.edit.not_found')]
            redirect_to notes_path
        end
    end

    def update
        @user = User.find_by_id!(session[:user]['id'])
        @note = @user.notes.find_by_id(params[:id])
        unless @note
            flash[:warning] = [t('controllers.notes.update.not_found')]
            redirect_to notes_path
        end

        if @note.update(note_params)
            flash[:success] = [t('controllers.notes.update.success')]
            redirect_to @note
        else
            flash.now[:warning] = [t('controllers.notes.update.invalid'), t('controllers.notes.update.invalid_info')]
            render 'edit'
        end

    end

    def destroy
        @user = User.find_by_id!(session[:user]['id'])
        succeed_notes = []
        failed_notes = []

        id = JSON.parse(params[:id])

        id.each do |t|
            note = @user.notes.find_by_id(t)
            if note
                note.destroy
                succeed_notes << t
            else
                failed_notes << t
            end
        end

        flash[:success] = [t('controllers.notes.destroy.success'), t('controllers.notes.destroy.success_info', id: succeed_notes.join(', '))] if succeed_notes.any?
        flash[:warning] = [t('controllers.notes.destroy.not_found'), t('controllers.notes.destroy.not_found_info', id: failed_notes.join(', '))] if failed_notes.any?

        redirect_to notes_path
    end

    def delete
        @user = User.find_by_id!(session[:user]['id'])
        @found_notes = []
        @not_found_notes = []

        # Prepare variable
        id = params[:id]
        if /^[0-9]+$/.match(id)
            id = [id]
        else
            id = JSON.parse(id)
        end

        # Sort ids by found/not found notes
        id.each do |t|
            (@user.notes.exists?(id: t) ? @found_notes : @not_found_notes) << t
        end

        # Check whether there was one id or more
        if id.length > 1
            # Check if none of notes have been found or only some of them
            if @found_notes.empty?
                flash[:warning] = [t('controllers.notes.delete.none_of_notes_found')]
                redirect_to notes_path
                return
            elsif @not_found_notes.any?
                flash.now[:warning] = [t('controllers.notes.delete.some_of_notes_not_found'),
                                       t('controllers.notes.delete.some_of_notes_not_found_info', id: @not_found_notes.join(', '))]
            end
        else
            # Check if ONE note has been found
            if @not_found_notes.any?
                flash[:warning] = [t('controllers.notes.delete.not_found')]
                redirect_to notes_path
            end
        end
    end

    def new
        @user = User.find_by_id!(session[:user]['id'])
        @note = @user.notes.new
        pass_variable 'note_create'
    end

    def create
        @user = User.find_by_id!(session[:user]['id'])
        @note = @user.notes.new(note_params)

        if @note.save
            flash[:success] = [t('controllers.notes.create.success')]
            redirect_to @note
        else
            flash.now[:warning] = [t('controllers.notes.create.invalid'), t('controllers.notes.create.invalid_info')]
            pass_variable 'note_create'
            render 'new'
        end
    end

    private
    def note_params
        params.require(:note).permit(:title, :content, :tag_list)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
    <fieldset>
      <legend><%= t('views.notes.form.title') %></legend>
      <dl>
        <div>
          <dt><%= f.label :title, t('views.notes.form.note_title') %></dt>
          <dd><%= f.text_field :title, placeholder: t('views.notes.form.note_title_placeholder') %></dd>
        </div>
        <div>
          <dt><%= f.label :content, t('views.notes.form.content') %></dt>
          <dd><%= f.text_area :content, placeholder: t('views.notes.form.content_placeholder'), rows: 15 %></dd>
        </div>
        <div>
          <dt><%= f.label :tag_list, t('views.notes.form.tags') %></dt>
          <dd><%= f.text_field :tag_list, placeholder: t('views.notes.form.tags_placeholder'), value: @note.tag_list.to_s %></dd>
        </div>
        <dd data-type="button" class="form-submit"><button name="submit" type="submit" id="submit"><%= t('views.notes.form.create') %></button></dd>
      </dl>
    </fieldset>
<% end %>

app/views/notes/_note.html.erb
<%
   do_truncate = false if do_truncate.nil?
   edit = false if edit.nil?
   options = false if options.nil?
   content = note.content
   content = markdown(content) unless edit
   content = truncate_html(content, length: 450, omission: ' [...]') if do_truncate
%>

<article id="note-<%= note.id %>" class="note" data-id="<%= note.id %>">
  <h3><a href="<%= note_path(note) %>"><%= note.title %></a></h3>

  <%= content %>

  <footer>
    <span>
      <%= t('views.notes.note.tags') %>
      <%= (note.tag_list.map {|tag| '#' + tag }).join(' ') %>
    </span>

    <span>
      <%= t('views.notes.note.created_at') %>
      <time datetime="<%= note.created_at %>"><%= note.created_at.strftime("%H:%M, %d.%m.%Y") %></time>
    </span>

    <% if note.created_at != note.updated_at %>
        <span>
          <%= t('views.notes.note.updated_at') %>
          <time datetime="<%= note.updated_at %>"><%= note.updated_at.strftime("%H:%M, %d.%m.%Y") %></time>
        </span>
    <% end %>

    <% if options %>
        <span class="options">
            <%= link_to t('views.notes.note.edit'), edit_note_path(note) %>
            <%= link_to t('views.notes.note.delete'), "/notes/#{note.id}/delete" %>
        </span>
    <% end %>

  </footer>
</article>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/delete.html.erb
<h2><%= t('views.notes.delete.title') %></h2>

<div id="delete-note" class="content">
  <%= t('views.notes.delete.confirmation', notes_id: @found_notes.join(', ')).html_safe %>
  <div class="choice_box">
    <%= link_to t('views.notes.delete.approval'), note_path(@found_notes.to_json), method: :delete, class: 'approval' %>
    <%= link_to t('views.notes.delete.refusal'), @note, class: 'refusal' %>
  </div>
</div>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<h2><%= t('views.notes.edit.title') %></h2>

<%= render 'shared/form_errors', :target => @note %>

<div id="edit-note" class="content">
  <%= render 'form' %>
</div>

app/views/notes/index.html.erb
<h2><%= t('views.notes.index.title') %></h2>

<div id="all-notes" class="content">
  <div class="bar">
    <ul class="options visuallyhidden">
      <li><button id="notes-check-all"><%= t('views.notes.index.options.check_all') %></button></li>
      <li><button id="notes-delete-checked"><%= t('views.notes.index.options.delete_checked') %></button></li>
    </ul>
  </div>
  <% @notes.each do |note| %>
      <%= render 'note', note: note, do_truncate: true %>
  <% end %>
</div>

app/views/notes/new.html.erb
<h2><%= t('views.notes.new.title') %></h2>

<%= render 'shared/form_errors', :target => @note %>

<div id="new-note" class="content">
<%= render 'form' %>
</div>

app/views/notes/show.html.erb
<h2><%= t('views.notes.show.title', title: @note.title) %></h2>

<div id="note-<%= @note.id %>" class="content">
  <%= render 'note', note: @note, options: true %>
</div>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>